---
kind: pipeline
name: build
workspace:
  base: /origin
clone:
  disable: true
steps:
  - name: clone
    image: docker:git
    commands:
      - git clone --recursive https://github.com/xsteadfastx/henri.git .
      - git checkout $DRONE_COMMIT
  - name: esp32-henri
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: True
      DEPS: True
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: esp32-deps
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: False
      DEPS: True
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: esp32-plain
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: False
      DEPS: False
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: unix
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: True
      DEPS: True
      PORT: unix
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: test
    image: quay.io/xsteadfastx/henri-builder
    commands:
      - build/pycopy -m test
