---
kind: pipeline
name: build
workspace:
  base: /origin
steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule init
      - git submodule update --recursive --remote
  - name: esp32-henri
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: True
      DEPS: True
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: esp32-deps
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: False
      DEPS: True
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: esp32-plain
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: False
      DEPS: False
      PORT: esp32
    commands:
      - sudo mkdir /build
      - sh .build.sh
  - name: unix
    image: quay.io/xsteadfastx/henri-builder
    environment:
      HENRI: True
      DEPS: True
      PORT: unix
    commands:
      - sudo mkdir /build
      - sh .build.sh
