# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<head>
<script>
var source = new EventSource(\"events\");
source.onmessage = function(event) """
    yield """{
    document.getElementById(\"result\").innerHTML = event.data + \"<br>\";
}
source.onerror = function(error) """
    yield """{
    console.log(error);
    document.getElementById(\"result\").innerHTML += \"EventSource error:\" + error + \"<br>\";
}
</script>
</head>
<body>
random int: <div id=\"result\"></div>
</body>
</html>
"""
